-- 코드를 입력하세요
SELECT F.FLAVOR
FROM (SELECT F.FLAVOR, SUM(F.TOTAL_ORDER) AS TOTAL_ORDER
      FROM FIRST_HALF F
      GROUP BY F.FLAVOR) F
         JOIN (SELECT J.FLAVOR, SUM(J.TOTAL_ORDER) AS TOTAL_ORDER
               FROM JULY J
               GROUP BY J.FLAVOR) J ON F.FLAVOR = J.FLAVOR
ORDER BY F.TOTAL_ORDER + J.TOTAL_ORDER DESC LIMIT 3;