-- 코드를 입력하세요
SELECT R.FOOD_TYPE, REST_ID, REST_NAME, T1.FAVORITES
FROM REST_INFO R
         JOIN (SELECT  MAX(FAVORITES) AS FAVORITES, FOOD_TYPE
               FROM REST_INFO GROUP BY FOOD_TYPE) T1
              ON T1.FOOD_TYPE = R.FOOD_TYPE AND T1.FAVORITES = R.FAVORITES
GROUP BY R.FOOD_TYPE
ORDER BY R.FOOD_TYPE DESC;